import { useEffect, useState } from 'react';
import { request } from './api';
import { PanelHead } from './panels';
type Stock = {symbol:string;name:string;sector:string;exchange:string;price:number|null;change_percent:number|null;timestamp:string|null;source:string};
type IndiaData = {status:string;message:string;stocks:Stock[];fetched_at:number};
export function IndianStocks(){
 const [data,setData]=useState<IndiaData|null>(null),[error,setError]=useState(''),[query,setQuery]=useState('');
 useEffect(()=>{let stopped=false;let timer:ReturnType<typeof setTimeout>;async function load(){try{const next=await request<IndiaData>('/india/quotes');if(!stopped){setData(next);setError('');}}catch(e){if(!stopped)setError((e as Error).message);}finally{if(!stopped)timer=setTimeout(load,10000);}}load();return()=>{stopped=true;clearTimeout(timer);};},[]);
 const rows=(data?.stocks||[]).filter(s=>`${s.symbol} ${s.name} ${s.sector}`.toLowerCase().includes(query.toLowerCase()));
 const stamp=(value:string|null)=>value?new Date(value.includes('+')||value.endsWith('Z')?value:value.replace(' ','T')+'+05:30').toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short'})+' IST':'—';
 return <section className="panel india-quotes"><PanelHead title="Indian stocks" sub="NSE equities · INR · Kite quote snapshots"/><p className="news-notice">{error||data?.message||'Checking Indian market connection…'}</p><div className="news-toolbar"><input aria-label="Search Indian stocks" placeholder="Search company, symbol or sector" value={query} onChange={e=>setQuery(e.target.value)}/><span className="badge">{data?.status==='connected'?'KITE CONNECTED':'QUOTES UNAVAILABLE'}</span></div><div className="table-scroll"><table><thead><tr><th>Company</th><th>Sector</th><th>Exchange</th><th>Last price (₹)</th><th>Change vs prior close</th><th>Exchange timestamp</th></tr></thead><tbody>{rows.map(s=><tr key={s.symbol}><td><b>{s.symbol}</b><div className="muted">{s.name}</div></td><td>{s.sector}</td><td>{s.exchange}</td><td>{s.price===null?'—':s.price.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td className={s.change_percent===null?'muted':s.change_percent>=0?'positive':'negative'}>{s.change_percent===null?'—':`${s.change_percent>=0?'+':''}${s.change_percent.toFixed(2)}%`}</td><td>{stamp(s.timestamp)}</td></tr>)}</tbody></table></div>{data&&!rows.length&&<p className="news-notice">No matching companies.</p>}<p className="news-notice">A curated list of 20 NSE companies. Prices remain blank until the authorized feed returns them. This quote view does not submit orders.</p></section>;
}
