import {useEffect,useState} from 'react';
import {Activity} from 'lucide-react';
import type {Opportunity,Snapshot} from './types';
import {fmt,time} from './api';
import {liveComparisons} from './live-comparisons';
export function LiveArbitrage({data,connected,onSelect}:{data:Snapshot;connected:boolean;onSelect:(o:Opportunity)=>void}){
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const maxAge=Number(data.settings.max_price_age_ms)||5000;
 const active=connected&&now-data.timestamp<=Math.max(5000,maxAge);
 const rows=active?liveComparisons(data.prices,now,maxAge):[];
 const fresh=data.prices.filter(p=>p.source==='live'&&!p.stale&&now-p.timestamp<=maxAge);
 return <section className="panel live-arbitrage"><div className="live-monitor-head"><div><span className="eyebrow">CONTINUOUS MARKET MONITOR</span><h3><Activity size={21}/>Live arbitrage watch</h3><p>Exchange quotes update automatically. The engine scans approximately once per second; each provider has its own update cadence.</p></div><span className={`badge ${active?'positive':'negative'}`}>{active?'STREAM CONNECTED':'WAITING FOR STREAM'}</span></div><div className="live-monitor-stats"><span>Latest scan <b>{time(data.timestamp)} IST</b></span><span>Fresh quotes <b>{active?fresh.length:0}</b></span><span>Comparison routes <b>{rows.length}</b></span><span>Stale cutoff <b>{fmt(maxAge/1000,1)}s</b></span></div><div className="live-venue-strip">{Object.entries(data.venues).map(([name,v])=><span key={name} className={v.state==='connected'?'positive':'muted'}><i className={`dot ${v.state==='connected'?'':'off'}`}/>{name} · {v.state}</span>)}</div><div className="table-scroll"><table><thead><tr><th>Asset</th><th>Buy venue · ask</th><th>Sell venue · bid</th><th>Gross difference</th><th>Quote age</th><th>Result</th></tr></thead><tbody>{rows.slice(0,20).map(r=>{const opportunity=data.opportunities.find(o=>o.source==='live'&&o.symbol===r.buy.symbol&&o.buy_venue===r.buy.exchange&&o.sell_venue===r.sell.exchange&&now-o.timestamp<=maxAge);return <tr key={r.buy.symbol+'|'+r.buy.quote}><td><b>{r.buy.symbol}</b><small>LIVE · {r.buy.quote}</small></td><td>{r.buy.exchange}<small>{fmt(r.buy.ask,6)} {r.buy.quote}</small></td><td>{r.sell.exchange}<small>{fmt(r.sell.bid,6)} {r.sell.quote}</small></td><td className={r.gross>0?'positive':'muted'}>{r.gross>0?'+':''}{fmt(r.gross,4)}%<small>Before costs</small></td><td>{fmt(Math.max(0,now-Math.min(r.buy.timestamp,r.sell.timestamp))/1000,1)}s</td><td>{opportunity?<button className="view-button" onClick={()=>onSelect(opportunity)}>Trade · net {fmt(opportunity.net_edge_percent,3)}%</button>:<span className="muted">{r.gross>0?'Not qualified after risk/cost checks':'No positive gross spread'}</span>}</td></tr>;})}</tbody></table></div>{!rows.length&&<p className="news-notice">{active?'Waiting for fresh quotes for the same asset from at least two exchanges.':'The stream is reconnecting. Comparisons pause until fresh quotes arrive.'}</p>}<p className="news-notice">Gross differences compare the best bid and ask before fees, slippage, depth and transfer costs. Only server-qualified opportunities expose Trade. No synthetic prices are included here.</p></section>;
}
