import { useEffect, useState } from 'react';
import type { Opportunity } from './types';
import { fmt } from './api';
const VENUES:Record<string,string>={Binance:'https://www.binance.com/',Coinbase:'https://www.coinbase.com/',Kraken:'https://www.kraken.com/',OKX:'https://www.okx.com/',Bybit:'https://www.bybit.com/'};
export function TradeReview({op,current,connected,onClose}:{op:Opportunity;current:boolean;connected:boolean;onClose:()=>void}){
 const [clock,setClock]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const fresh=current&&connected&&op.source==='live'&&clock-op.timestamp<=5000;
 const buy=VENUES[op.buy_venue],sell=VENUES[op.sell_venue];
 return <section className="trade-review"><span className="eyebrow">TRADE · REVIEW BEFORE BUYING</span><h3>Buy and sell route</h3><p>Review both legs in your exchange accounts. These buttons open the official exchange website; they do not submit or prefill an order.</p><div className="trade-leg-actions"><div><small>BUY · {op.buy_venue}</small><strong>{fmt(op.buy_price,4)} {op.quote}</strong>{fresh&&buy?<a className="landing-cta" href={buy} target="_blank" rel="noopener noreferrer">Buy on {op.buy_venue}</a>:<button className="landing-cta" disabled>Buy unavailable</button>}</div><div><small>SELL · {op.sell_venue}</small><strong>{fmt(op.sell_price,4)} {op.quote}</strong>{fresh&&sell?<a className="secondary-button" href={sell} target="_blank" rel="noopener noreferrer">Sell on {op.sell_venue}</a>:<button className="secondary-button" disabled>Sell unavailable</button>}</div></div><p>{fresh?'Live observation: recheck price, fees and balances at both venues before placing an order.':'This route is stale, disconnected or simulated. Wait for a qualified live opportunity to enable exchange links.'}</p>{op.type==='triangular'&&<p>Triangular routes require all three conversions shown below. Buying and selling the displayed pair alone does not complete this route.</p>}<p>Cross-exchange legs are not atomic: one leg can fill while the other fails. Funds must be available at each venue. Estimated profit is not guaranteed.</p><div className="trade-payment-note"><b>Trading funds</b><p>Use the exchange or broker’s own authorized funding flow. Stripe Checkout in this app pays only for the app subscription.</p><a href="#Subscription" onClick={onClose}>Manage app subscription</a></div></section>;
}
